"""
Notbook Deploy Console — local management UI for secrets, config, and deploy targets.

Run:
  python run_deploy_console.py
  # then open http://127.0.0.1:8787
"""

from __future__ import annotations

import os
import re
import signal
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path
from typing import Any, Optional

import yaml
from functools import wraps

from flask import Flask, Response, jsonify, render_template, request
from werkzeug.utils import secure_filename

ROOT = Path(__file__).resolve().parent.parent
CONSOLE = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"
CONFIG_PATH = ROOT / "config.yaml"
PID_PATH = ROOT / "data" / "bot.pid"
ARTIFACTS = ROOT / "deploy_artifacts"
LOG_PATH = ROOT / "data" / "bot_console.log"

app = Flask(
    __name__,
    template_folder=str(CONSOLE / "templates"),
    static_folder=str(CONSOLE / "static"),
)


def _console_auth_enabled() -> bool:
    return bool(
        (os.getenv("CONSOLE_PASSWORD") or _read_env().get("CONSOLE_PASSWORD") or "").strip()
    )


def _check_basic_auth() -> bool:
    """HTTP Basic auth when CONSOLE_PASSWORD is set."""
    expected = (
        os.getenv("CONSOLE_PASSWORD") or _read_env().get("CONSOLE_PASSWORD") or ""
    ).strip()
    if not expected:
        return True
    user_expected = (
        os.getenv("CONSOLE_USER") or _read_env().get("CONSOLE_USER") or "admin"
    ).strip()
    auth = request.authorization
    if not auth:
        return False
    return auth.username == user_expected and auth.password == expected


@app.before_request
def _require_console_auth():
    # Always allow health probes without browser auth
    if request.path in ("/health", "/healthz"):
        return None
    # Service-to-service routes use INTERNAL_SERVICE_TOKEN only (not Basic Auth)
    if request.path.startswith("/api/internal/"):
        return None
    if not _console_auth_enabled():
        return None
    if _check_basic_auth():
        return None
    return Response(
        "Authentication required.\nSet CONSOLE_USER / CONSOLE_PASSWORD on the service.",
        401,
        {"WWW-Authenticate": 'Basic realm="Notbook Deploy Console"'},
    )


@app.get("/health")
@app.get("/healthz")
def healthz():
    return Response("ok", 200, mimetype="text/plain")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ensure_dirs() -> None:
    (ROOT / "data").mkdir(parents=True, exist_ok=True)
    ARTIFACTS.mkdir(parents=True, exist_ok=True)


def _read_env() -> dict[str, str]:
    data: dict[str, str] = {}
    if not ENV_PATH.is_file():
        return data
    for line in ENV_PATH.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        data[k.strip()] = v.strip().strip('"').strip("'")
    return data


def _write_env(values: dict[str, str]) -> None:
    # Preserve comments from example order when possible
    order = [
        "TELEGRAM_BOT_TOKEN",
        "GEMINI_API_KEY",
        "GEMINI_API_KEYS",
        "PINECONE_API_KEY",
        "ADMIN_USER_IDS",
        "PORT",
        "RENDER_API_KEY",
        "RENDER_SERVICE_ID",
        "INTERNAL_SERVICE_TOKEN",
        "BOT_BASE_URL",
        "CONSOLE_BASE_URL",
        "CONSOLE_PASSWORD",
        "CONSOLE_USER",
    ]
    lines = [
        "# Notbook AI — generated by Deploy Console",
        f"# {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]
    seen = set()
    for k in order:
        if k in values and values[k] is not None and str(values[k]) != "":
            lines.append(f"{k}={values[k]}")
            seen.add(k)
    for k, v in values.items():
        if k in seen:
            continue
        if v is None or str(v) == "":
            continue
        lines.append(f"{k}={v}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _mask(val: str, show: int = 4) -> str:
    if not val:
        return ""
    if len(val) <= show * 2:
        return "*" * len(val)
    return val[:show] + "…" + val[-show:]


def _load_yaml() -> dict[str, Any]:
    if not CONFIG_PATH.is_file():
        return {}
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _save_yaml(data: dict[str, Any]) -> None:
    # Merge into existing to preserve nested keys not in form
    existing = _load_yaml()

    def deep_merge(base: dict, patch: dict) -> dict:
        for k, v in patch.items():
            if isinstance(v, dict) and isinstance(base.get(k), dict):
                deep_merge(base[k], v)
            else:
                base[k] = v
        return base

    merged = deep_merge(existing, data)
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        yaml.safe_dump(merged, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def _bot_pid() -> Optional[int]:
    if not PID_PATH.is_file():
        return None
    try:
        pid = int(PID_PATH.read_text(encoding="utf-8").strip())
    except ValueError:
        return None
    # Check alive
    try:
        if sys.platform == "win32":
            out = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if str(pid) in out.stdout and "python" in out.stdout.lower():
                return pid
            # also accept any process with that pid
            if str(pid) in out.stdout and "No tasks" not in out.stdout:
                return pid
        else:
            os.kill(pid, 0)
            return pid
    except Exception:
        pass
    return None


def _set_nested(d: dict, path: str, value: Any) -> None:
    parts = path.split(".")
    cur = d
    for p in parts[:-1]:
        cur = cur.setdefault(p, {})
    # coerce numbers/bools
    if isinstance(value, str):
        low = value.lower().strip()
        if low in ("true", "false"):
            value = low == "true"
        else:
            try:
                if "." in value:
                    value = float(value)
                else:
                    value = int(value)
            except ValueError:
                pass
    cur[parts[-1]] = value


# ---------------------------------------------------------------------------
# Artifact generators
# ---------------------------------------------------------------------------

def generate_artifacts() -> dict[str, str]:
    _ensure_dirs()
    files: dict[str, str] = {}

    files["docker-compose.yml"] = """# Notbook AI — Docker Compose
services:
  notbook:
    build: .
    container_name: notbook-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - PORT=8080
"""

    files["Procfile"] = "web: python main.py\n"

    files["render.yaml"] = """# Render Blueprint — Notbook AI
# https://render.com/docs/blueprint-spec
# NOTE: Deploy Console is a separate Web Service (not Static Site).
services:
  - type: web
    name: notbook-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"

  - type: web
    name: notbook-console
    runtime: python
    plan: free
    buildCommand: pip install -r requirements-console.txt
    startCommand: python run_deploy_console.py
    envVars:
      - key: CONSOLE_PASSWORD
        sync: false
      - key: CONSOLE_USER
        value: admin
      - key: CONSOLE_HOST
        value: "0.0.0.0"
      - key: CONSOLE_NO_BROWSER
        value: "1"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_SERVICE_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
"""

    files["RENDER_CONSOLE.md"] = """# Host Deploy Console on Render

## Wrong type: Static Site
Static Site only serves HTML files. The console is a **Flask Python app**.
Cancel "New Static Site" and use **Web Service** instead.

## Correct: New → Web Service

| Field | Value |
|-------|--------|
| Source | dietyslaying/notbook |
| Name | notbook-console |
| Language | Python 3 |
| Branch | main |
| Root Directory | (leave empty) |
| Build Command | `pip install -r requirements-console.txt` |
| Start Command | `python run_deploy_console.py` |
| Instance | Free (sleeps) or paid |

Bot service uses `requirements.txt` instead.

## Environment variables (required)

```
CONSOLE_PASSWORD=pick-a-strong-password
CONSOLE_USER=admin
CONSOLE_NO_BROWSER=1
CONSOLE_HOST=0.0.0.0

# Same bot secrets as the main service (for library upload / sync)
TELEGRAM_BOT_TOKEN=...
GEMINI_API_KEY=...
PINECONE_API_KEY=...
ADMIN_USER_IDS=...

# Optional: control the bot service from the console
RENDER_API_KEY=...
RENDER_SERVICE_ID=srv-...
```

Render sets `PORT` automatically — do not hardcode it.

## Security
The console can upload books, read env, and trigger deploys.
**Always set CONSOLE_PASSWORD** if the service is public.
Browser will prompt for Basic Auth (user + password).

## After deploy
Open https://notbook-console.onrender.com (your URL) → enter password → use LIBRARY / RENDER tabs.
"""

    files["railway.toml"] = """# Railway — Notbook AI
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python main.py"
"""

    files["fly.toml"] = """# Fly.io — Notbook AI
app = "notbook-bot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
"""

    files["notbook.service"] = """# systemd unit for VPS — install to /etc/systemd/system/notbook.service
[Unit]
Description=Notbook AI Telegram Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=notbook
WorkingDirectory=/opt/notbook
EnvironmentFile=/opt/notbook/.env
ExecStart=/opt/notbook/.venv/bin/python main.py
Restart=always
RestartSec=5
StandardOutput=append:/var/log/notbook/bot.log
StandardError=append:/var/log/notbook/bot.err

[Install]
WantedBy=multi-user.target
"""

    files["vps_setup.sh"] = """#!/usr/bin/env bash
# Minimal VPS bootstrap for Notbook AI (Debian/Ubuntu)
set -euo pipefail
APP_DIR=/opt/notbook
sudo useradd -r -m -d "$APP_DIR" -s /bin/bash notbook || true
sudo mkdir -p "$APP_DIR" /var/log/notbook
sudo chown -R notbook:notbook "$APP_DIR" /var/log/notbook

# Clone or copy project into $APP_DIR, then:
#   sudo -u notbook python3 -m venv $APP_DIR/.venv
#   sudo -u notbook $APP_DIR/.venv/bin/pip install -r requirements.txt
#   sudo cp notbook.service /etc/systemd/system/
#   sudo systemctl daemon-reload
#   sudo systemctl enable --now notbook

echo "Copy project files to $APP_DIR, place .env, then enable systemd unit."
"""

    files["vercel.json"] = """{
  "_comment": "Vercel is NOT recommended for long-polling Telegram bots. Prefer Render/Railway/Fly/VPS. This file is a stub for static docs only.",
  "version": 2,
  "builds": [],
  "routes": []
}
"""

    files["DEPLOY.md"] = """# Notbook deploy notes

## Local
```
pip install -r requirements.txt
python main.py
```
Or use Deploy Console → Local → START.

## Docker
```
docker compose -f deploy_artifacts/docker-compose.yml up -d --build
```

## Render
1. New Web Service from GitHub repo
2. Build: `pip install -r requirements.txt`
3. Start: `python main.py`
4. Add env vars from Console → Secrets
5. Free tier sleeps — bot polling pauses until wake

## Railway
1. New project from repo
2. Add variables from Secrets
3. Deploy (Dockerfile or Nixpacks)

## Heroku
```
heroku create notbook-bot
heroku config:set TELEGRAM_BOT_TOKEN=... GEMINI_API_KEY=... PINECONE_API_KEY=...
git push heroku main
```
Uses Procfile (`web: python main.py`).

## Fly.io
```
fly launch --config deploy_artifacts/fly.toml
fly secrets set TELEGRAM_BOT_TOKEN=... GEMINI_API_KEY=... PINECONE_API_KEY=...
fly deploy
```

## VPS (systemd)
See `vps_setup.sh` + `notbook.service`.

## Vercel
Not suitable for Telegram long-polling. Use a always-on host.

## After first deploy
Re-ingest PDFs (admin) into `library-index-v2` with Gemini embeddings.
"""

    for name, content in files.items():
        path = ARTIFACTS / name
        path.write_text(content, encoding="utf-8")
    return files


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/")
def index():
    return render_template("index.html")


def _render_client():
    from render_api import RenderAPIError, RenderClient

    env = _read_env()
    key = (env.get("RENDER_API_KEY") or os.getenv("RENDER_API_KEY") or "").strip()
    if not key:
        raise RenderAPIError("Set RENDER_API_KEY in Secrets / .env")
    return RenderClient(key), env


@app.get("/api/status")
def api_status():
    env = _read_env()
    cfg = _load_yaml()
    pid = _bot_pid()
    secrets = {
        "TELEGRAM_BOT_TOKEN": bool(env.get("TELEGRAM_BOT_TOKEN")),
        "GEMINI_API_KEY": bool(env.get("GEMINI_API_KEY") or env.get("GEMINI_API_KEYS")),
        "PINECONE_API_KEY": bool(env.get("PINECONE_API_KEY")),
        "ADMIN_USER_IDS": bool(env.get("ADMIN_USER_IDS")),
        "RENDER_API_KEY": bool(env.get("RENDER_API_KEY")),
        "RENDER_SERVICE_ID": bool(env.get("RENDER_SERVICE_ID")),
    }
    return jsonify(
        {
            "ok": True,
            "project_root": str(ROOT),
            "bot_running": pid is not None,
            "bot_pid": pid,
            "secrets": secrets,
            "ready": all(
                [
                    secrets["TELEGRAM_BOT_TOKEN"],
                    secrets["GEMINI_API_KEY"],
                    secrets["PINECONE_API_KEY"],
                ]
            ),
            "llm_model": (cfg.get("llm") or {}).get("model_name"),
            "embed": cfg.get("embeddings") or {},
            "index": (cfg.get("pinecone") or {}).get("index_name"),
            "reranker": (cfg.get("reranker") or {}).get("backend"),
            "platform": sys.platform,
            "python": sys.version.split()[0],
            "render_configured": secrets["RENDER_API_KEY"],
            "render_service_id": env.get("RENDER_SERVICE_ID") or "",
            "link": {
                "bot_base_url": (env.get("BOT_BASE_URL") or "").rstrip("/"),
                "console_base_url": (
                    env.get("CONSOLE_BASE_URL")
                    or os.getenv("RENDER_EXTERNAL_URL")
                    or ""
                ).rstrip("/"),
                "token_set": bool(
                    (env.get("INTERNAL_SERVICE_TOKEN") or "").strip()
                ),
                "on_render": bool(os.getenv("RENDER")),
            },
        }
    )


# ---------------------------------------------------------------------------
# Render.com API
# ---------------------------------------------------------------------------

@app.get("/api/render/services")
def api_render_services():
    try:
        client, env = _render_client()
        services = [client.summarize_service(s) for s in client.list_services()]
        preferred = env.get("RENDER_SERVICE_ID") or ""
        return jsonify(
            {
                "ok": True,
                "services": services,
                "preferred_service_id": preferred,
                "count": len(services),
            }
        )
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.get("/api/render/service/<service_id>")
def api_render_service(service_id: str):
    try:
        client, _ = _render_client()
        svc = client.get_service(service_id)
        deploys = client.list_deploys(service_id, limit=8)
        return jsonify(
            {
                "ok": True,
                "service": client.summarize_service(svc),
                "raw_keys": list(svc.keys()) if isinstance(svc, dict) else [],
                "deploys": [
                    {
                        "id": d.get("id"),
                        "status": d.get("status"),
                        "trigger": d.get("trigger"),
                        "createdAt": d.get("createdAt"),
                        "finishedAt": d.get("finishedAt"),
                        "commit": (d.get("commit") or {}).get("message")
                        if isinstance(d.get("commit"), dict)
                        else d.get("commit"),
                    }
                    for d in deploys
                ],
            }
        )
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.post("/api/render/deploy")
def api_render_deploy():
    body = request.get_json(force=True, silent=True) or {}
    try:
        client, env = _render_client()
        sid = (body.get("service_id") or env.get("RENDER_SERVICE_ID") or "").strip()
        if not sid:
            return jsonify({"ok": False, "error": "service_id required"}), 400
        clear = bool(body.get("clear_cache"))
        deploy = client.trigger_deploy(sid, clear_cache=clear)
        return jsonify({"ok": True, "deploy": deploy, "service_id": sid})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.post("/api/render/suspend")
def api_render_suspend():
    body = request.get_json(force=True, silent=True) or {}
    try:
        client, env = _render_client()
        sid = (body.get("service_id") or env.get("RENDER_SERVICE_ID") or "").strip()
        if not sid:
            return jsonify({"ok": False, "error": "service_id required"}), 400
        client.suspend(sid)
        return jsonify({"ok": True, "message": f"suspend requested for {sid}"})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.post("/api/render/resume")
def api_render_resume():
    body = request.get_json(force=True, silent=True) or {}
    try:
        client, env = _render_client()
        sid = (body.get("service_id") or env.get("RENDER_SERVICE_ID") or "").strip()
        if not sid:
            return jsonify({"ok": False, "error": "service_id required"}), 400
        client.resume(sid)
        return jsonify({"ok": True, "message": f"resume requested for {sid}"})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.get("/api/render/env/<service_id>")
def api_render_env_get(service_id: str):
    try:
        client, _ = _render_client()
        vars_ = client.list_env_vars(service_id)
        masked = request.args.get("masked", "1") != "0"
        out = []
        sensitive = {
            "TELEGRAM_BOT_TOKEN",
            "GEMINI_API_KEY",
            "GEMINI_API_KEYS",
            "PINECONE_API_KEY",
            "RENDER_API_KEY",
        }
        for v in vars_:
            key = str(v.get("key") or "")
            val = str(v.get("value") or "")
            if masked and (key in sensitive or "TOKEN" in key or "KEY" in key or "SECRET" in key):
                val = _mask(val)
            out.append({"key": key, "value": val})
        return jsonify({"ok": True, "env": out, "masked": masked})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.post("/api/render/env/sync")
def api_render_env_sync():
    """
    Push local .env bot secrets to the selected Render service (merge, not wipe).
    Body: { service_id?, keys?: ["TELEGRAM_BOT_TOKEN", ...] }
    """
    body = request.get_json(force=True, silent=True) or {}
    try:
        client, env = _render_client()
        sid = (body.get("service_id") or env.get("RENDER_SERVICE_ID") or "").strip()
        if not sid:
            return jsonify({"ok": False, "error": "service_id required"}), 400
        default_keys = [
            "TELEGRAM_BOT_TOKEN",
            "GEMINI_API_KEY",
            "GEMINI_API_KEYS",
            "PINECONE_API_KEY",
            "ADMIN_USER_IDS",
            "INTERNAL_SERVICE_TOKEN",
            "CONSOLE_BASE_URL",
            "BOT_BASE_URL",
        ]
        keys = body.get("keys") or default_keys
        updates = {}
        for k in keys:
            v = env.get(k)
            if v:
                updates[k] = v
        if not updates:
            return jsonify({"ok": False, "error": "no local secret values to sync"}), 400
        result = client.upsert_env_vars(sid, updates)
        deploy = None
        if body.get("deploy", True):
            deploy = client.trigger_deploy(sid, clear_cache=False)
        return jsonify(
            {
                "ok": True,
                "synced_keys": list(updates.keys()),
                "env_count": len(result),
                "deploy": deploy,
            }
        )
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.post("/api/render/prefer")
def api_render_prefer():
    """Save preferred RENDER_SERVICE_ID into .env"""
    body = request.get_json(force=True, silent=True) or {}
    sid = (body.get("service_id") or "").strip()
    if not sid:
        return jsonify({"ok": False, "error": "service_id required"}), 400
    env = _read_env()
    env["RENDER_SERVICE_ID"] = sid
    _write_env(env)
    return jsonify({"ok": True, "RENDER_SERVICE_ID": sid})


@app.get("/api/render/logs/<service_id>")
def api_render_logs(service_id: str):
    try:
        client, _ = _render_client()
        limit = int(request.args.get("limit") or 80)
        log_type = request.args.get("type") or None  # app|build|request
        data = client.get_logs(service_id, limit=limit, log_type=log_type)
        # plain text for terminal display
        text_lines = []
        for row in data.get("logs") or []:
            ts = (row.get("timestamp") or "")[:19].replace("T", " ")
            typ = row.get("type") or ""
            msg = row.get("message") or ""
            prefix = f"[{ts}]" + (f" ({typ})" if typ else "")
            text_lines.append(f"{prefix} {msg}")
        return jsonify(
            {
                "ok": True,
                "text": "\n".join(text_lines) if text_lines else "(no log lines)",
                "count": len(text_lines),
                "hasMore": data.get("hasMore"),
            }
        )
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.get("/api/render/env/<service_id>/full")
def api_render_env_full(service_id: str):
    """Full env dump (unmasked). For local console only — do not expose publicly."""
    try:
        client, _ = _render_client()
        vars_ = client.list_env_vars(service_id)
        # Sort keys for readability
        rows = sorted(
            [{"key": str(v.get("key") or ""), "value": str(v.get("value") or "")} for v in vars_],
            key=lambda x: x["key"],
        )
        text = "\n".join(f"{r['key']}={r['value']}" for r in rows)
        return jsonify({"ok": True, "env": rows, "text": text, "count": len(rows)})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.post("/api/render/deploy/clear")
def api_render_deploy_clear():
    """Clear build cache and deploy latest commit on the linked branch."""
    body = request.get_json(force=True, silent=True) or {}
    try:
        client, env = _render_client()
        sid = (body.get("service_id") or env.get("RENDER_SERVICE_ID") or "").strip()
        if not sid:
            return jsonify({"ok": False, "error": "service_id required"}), 400
        deploy = client.trigger_deploy(sid, clear_cache=True)
        return jsonify(
            {
                "ok": True,
                "message": "Clear cache + deploy latest commit triggered",
                "deploy": deploy,
                "service_id": sid,
            }
        )
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.get("/api/render/ssh")
def api_render_ssh():
    """Return console SSH public key + connection hint for selected service."""
    pub_path = ROOT / "data" / "ssh" / "render_notbook_ed25519.pub"
    priv_path = ROOT / "data" / "ssh" / "render_notbook_ed25519"
    if not pub_path.is_file():
        return jsonify(
            {
                "ok": False,
                "error": "SSH key missing. Run: ssh-keygen -t ed25519 -f data/ssh/render_notbook_ed25519",
            }
        ), 404
    pub = pub_path.read_text(encoding="utf-8").strip()
    env = _read_env()
    sid = (request.args.get("service_id") or env.get("RENDER_SERVICE_ID") or "").strip()
    ssh_cmd = None
    region = None
    if sid:
        try:
            client, _ = _render_client()
            sm = client.summarize_service(client.get_service(sid))
            ssh_cmd = sm.get("ssh_command")
            region = sm.get("region")
        except Exception:
            pass
    return jsonify(
        {
            "ok": True,
            "public_key": pub,
            "private_key_path": str(priv_path),
            "public_key_path": str(pub_path),
            "add_key_url": "https://dashboard.render.com/settings#ssh-public-keys",
            "ssh_command": ssh_cmd,
            "region": region,
            "service_id": sid or None,
            "instructions": [
                "Open https://dashboard.render.com/settings#ssh-public-keys",
                "Click + Add SSH Public Key",
                "Name: Notbook Deploy Console",
                "Paste the public_key below",
                "Save, then use ssh_command (paid plans; free web services may not allow shell)",
            ],
        }
    )


@app.get("/api/env")
def api_env_get():
    env = _read_env()
    masked = request.args.get("masked", "1") != "0"
    out = {}
    for k, v in env.items():
        if masked and k.upper() in {
            "TELEGRAM_BOT_TOKEN",
            "GEMINI_API_KEY",
            "GEMINI_API_KEYS",
            "PINECONE_API_KEY",
        }:
            out[k] = _mask(v)
        else:
            out[k] = v
    return jsonify({"ok": True, "env": out, "masked": masked, "path": str(ENV_PATH)})


@app.post("/api/env")
def api_env_post():
    body = request.get_json(force=True, silent=True) or {}
    values = body.get("env") or body
    if not isinstance(values, dict):
        return jsonify({"ok": False, "error": "expected env object"}), 400
    current = _read_env()
    # Don't overwrite with masked placeholders
    for k, v in values.items():
        if v is None:
            continue
        vs = str(v)
        if "…" in vs or (vs and set(vs) <= {"*"}):
            continue
        current[k] = vs
    _write_env(current)
    return jsonify({"ok": True, "message": f"Wrote {ENV_PATH.name}"})


@app.get("/api/config")
def api_config_get():
    return jsonify({"ok": True, "config": _load_yaml(), "path": str(CONFIG_PATH)})


@app.post("/api/config")
def api_config_post():
    body = request.get_json(force=True, silent=True) or {}
    # Accept either full config or flat dotted paths under "fields"
    if "fields" in body and isinstance(body["fields"], dict):
        patch: dict[str, Any] = {}
        for path, val in body["fields"].items():
            _set_nested(patch, path, val)
        _save_yaml(patch)
    elif "config" in body and isinstance(body["config"], dict):
        _save_yaml(body["config"])
    else:
        return jsonify({"ok": False, "error": "expected fields or config"}), 400
    return jsonify({"ok": True, "message": f"Saved {CONFIG_PATH.name}"})


@app.post("/api/local/start")
def api_local_start():
    _ensure_dirs()
    if _bot_pid():
        return jsonify({"ok": False, "error": "Bot already running", "pid": _bot_pid()}), 409
    env = os.environ.copy()
    file_env = _read_env()
    env.update(file_env)
    logf = open(LOG_PATH, "a", encoding="utf-8")
    logf.write(f"\n--- start {time.strftime('%Y-%m-%d %H:%M:%S')} ---\n")
    logf.flush()
    creation = 0
    if sys.platform == "win32":
        creation = subprocess.CREATE_NEW_PROCESS_GROUP  # type: ignore[attr-defined]
    proc = subprocess.Popen(
        [sys.executable, str(ROOT / "main.py")],
        cwd=str(ROOT),
        env=env,
        stdout=logf,
        stderr=subprocess.STDOUT,
        creationflags=creation,
    )
    PID_PATH.write_text(str(proc.pid), encoding="utf-8")
    return jsonify({"ok": True, "pid": proc.pid, "log": str(LOG_PATH)})


@app.post("/api/local/stop")
def api_local_stop():
    pid = _bot_pid()
    if not pid:
        if PID_PATH.is_file():
            PID_PATH.unlink(missing_ok=True)
        return jsonify({"ok": True, "message": "Bot was not running"})
    try:
        if sys.platform == "win32":
            subprocess.run(["taskkill", "/PID", str(pid), "/T", "/F"], capture_output=True)
        else:
            os.kill(pid, signal.SIGTERM)
            time.sleep(0.5)
            try:
                os.kill(pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 500
    PID_PATH.unlink(missing_ok=True)
    return jsonify({"ok": True, "message": f"Stopped pid {pid}"})


@app.get("/api/local/log")
def api_local_log():
    if not LOG_PATH.is_file():
        return jsonify({"ok": True, "log": "(no log yet)"})
    text = LOG_PATH.read_text(encoding="utf-8", errors="replace")
    # last 200 lines
    lines = text.splitlines()
    tail = "\n".join(lines[-200:])
    return jsonify({"ok": True, "log": tail})


@app.post("/api/artifacts/generate")
def api_artifacts_generate():
    files = generate_artifacts()
    return jsonify(
        {
            "ok": True,
            "dir": str(ARTIFACTS),
            "files": list(files.keys()),
        }
    )


@app.get("/api/artifacts")
def api_artifacts_list():
    _ensure_dirs()
    names = sorted(p.name for p in ARTIFACTS.iterdir() if p.is_file()) if ARTIFACTS.is_dir() else []
    return jsonify({"ok": True, "dir": str(ARTIFACTS), "files": names})


@app.get("/api/artifacts/<path:name>")
def api_artifacts_get(name: str):
    if ".." in name or name.startswith(("/", "\\")):
        return jsonify({"ok": False, "error": "bad name"}), 400
    path = ARTIFACTS / name
    if not path.is_file():
        return jsonify({"ok": False, "error": "not found"}), 404
    return jsonify({"ok": True, "name": name, "content": path.read_text(encoding="utf-8")})


# ---------------------------------------------------------------------------
# Library upload jobs (background + realtime progress)
# ---------------------------------------------------------------------------

_upload_jobs: dict[str, dict[str, Any]] = {}
_upload_lock = threading.Lock()
_MAX_JOB_LOGS = 500


def _job_snapshot(job: dict[str, Any], *, since: int = 0) -> dict[str, Any]:
    logs = job.get("logs") or []
    return {
        "id": job["id"],
        "status": job["status"],  # queued|running|done|error
        "phase": job.get("phase") or "",
        "pct": job.get("pct") if job.get("pct") is not None else 0,
        "current": job.get("current"),
        "total": job.get("total"),
        "display_name": job.get("display_name") or "",
        "filename": job.get("filename") or "",
        "message": job.get("message") or "",
        "result": job.get("result"),
        "error": job.get("error"),
        "started_at": job.get("started_at"),
        "updated_at": job.get("updated_at"),
        "finished_at": job.get("finished_at"),
        "log_total": len(logs),
        "logs": logs[since:],
        "log_offset": since,
    }


def _append_job_log(job_id: str, event: Any) -> None:
    now = time.time()
    if isinstance(event, dict):
        msg = str(event.get("msg") or "")
        phase = str(event.get("phase") or "")
        pct = event.get("pct")
        current = event.get("current")
        total = event.get("total")
    else:
        msg = str(event)
        phase = pct = current = total = None

    ts = time.strftime("%H:%M:%S")
    line = f"[{ts}] {msg}"
    with _upload_lock:
        job = _upload_jobs.get(job_id)
        if not job:
            return
        job["logs"].append(line)
        if len(job["logs"]) > _MAX_JOB_LOGS:
            job["logs"] = job["logs"][-_MAX_JOB_LOGS:]
        job["message"] = msg
        job["updated_at"] = now
        if phase:
            job["phase"] = phase
        if pct is not None:
            try:
                job["pct"] = float(pct)
            except (TypeError, ValueError):
                pass
        if current is not None:
            job["current"] = current
        if total is not None:
            job["total"] = total


def _run_upload_job(job_id: str, dest: Path, display_name: str) -> None:
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "notbook_ai"))
    env = _read_env()
    for k, v in env.items():
        if v and k not in os.environ:
            os.environ[k] = v

    with _upload_lock:
        job = _upload_jobs.get(job_id)
        if job:
            job["status"] = "running"
            job["started_at"] = time.time()
            job["updated_at"] = time.time()
            job["phase"] = "start"
            job["pct"] = 1
            job["message"] = "Starting ingest…"

    _append_job_log(job_id, {"msg": f"Job {job_id} started", "phase": "start", "pct": 1})
    _append_job_log(
        job_id,
        {
            "msg": f"File: {dest.name} → display name: {display_name}",
            "phase": "start",
            "pct": 2,
        },
    )

    try:
        from services.ingest import ingest_service

        def progress(event) -> None:
            _append_job_log(job_id, event)

        result = ingest_service.ingest_pdf(
            str(dest), display_name, progress=progress, wipe_namespace=True
        )
        try:
            from services.gemini_service import gemini_service

            gemini_service._ns_cache = None
        except Exception:
            pass

        with _upload_lock:
            job = _upload_jobs.get(job_id)
            if job:
                job["status"] = "done"
                job["pct"] = 100
                job["phase"] = "done"
                job["result"] = result
                job["message"] = (
                    f"OK — {result.get('book')} · {result.get('chunks')} chunks"
                )
                job["finished_at"] = time.time()
                job["updated_at"] = time.time()
        _append_job_log(
            job_id,
            {
                "msg": (
                    f"Complete. ns={result.get('namespace')} "
                    f"index={result.get('index')} chunks={result.get('chunks')}"
                ),
                "phase": "done",
                "pct": 100,
                "current": result.get("chunks"),
                "total": result.get("chunks"),
            },
        )
        # Notify linked bot to refresh namespace cache
        try:
            from link_client import bot_request, link_configured

            if link_configured():
                bot_request(
                    "POST",
                    "/internal/webhook/console",
                    body={
                        "event": "library_upload",
                        "book": result.get("book"),
                        "namespace": result.get("namespace"),
                        "chunks": result.get("chunks"),
                    },
                )
                _append_job_log(
                    job_id,
                    {"msg": "Notified linked bot (library_upload)", "phase": "done", "pct": 100},
                )
        except Exception as ne:
            _append_job_log(
                job_id,
                {"msg": f"Bot notify skipped: {ne}", "phase": "done", "pct": 100},
            )
    except Exception as e:
        err = f"{type(e).__name__}: {e}"
        with _upload_lock:
            job = _upload_jobs.get(job_id)
            if job:
                job["status"] = "error"
                job["error"] = err
                job["message"] = err
                job["finished_at"] = time.time()
                job["updated_at"] = time.time()
        _append_job_log(job_id, {"msg": f"ERROR: {err}", "phase": "error"})
    finally:
        try:
            dest.unlink(missing_ok=True)
        except Exception:
            pass


@app.get("/api/library/books")
def api_library_books():
    """List Pinecone namespaces as display books for Telegram menu."""
    try:
        sys.path.insert(0, str(ROOT))
        sys.path.insert(0, str(ROOT / "notbook_ai"))
        from services.library import list_books

        books = list_books()
        return jsonify({"ok": True, "books": books, "count": len(books)})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e), "books": []}), 500


@app.post("/api/library/upload")
def api_library_upload():
    """
    Start background PDF ingest. Returns job_id immediately.
    Poll GET /api/library/upload/<job_id>?since=N for progress + logs.
    Form: file (pdf), display_name (str)
    """
    try:
        f = request.files.get("file")
        display_name = (request.form.get("display_name") or "").strip()
        if not f or not f.filename:
            return jsonify({"ok": False, "error": "No PDF file"}), 400
        if not display_name:
            return jsonify(
                {"ok": False, "error": "display_name required (Telegram book label)"}
            ), 400
        if not f.filename.lower().endswith(".pdf"):
            return jsonify({"ok": False, "error": "Only PDF supported"}), 400

        tmp_dir = ROOT / "data" / "ingest_tmp"
        tmp_dir.mkdir(parents=True, exist_ok=True)
        safe = secure_filename(f.filename) or "upload.pdf"
        job_id = uuid.uuid4().hex[:12]
        dest = tmp_dir / f"gui_{job_id}_{safe}"
        f.save(str(dest))

        job = {
            "id": job_id,
            "status": "queued",
            "phase": "queued",
            "pct": 0,
            "current": None,
            "total": None,
            "display_name": display_name,
            "filename": safe,
            "message": "Queued…",
            "logs": [],
            "result": None,
            "error": None,
            "started_at": None,
            "updated_at": time.time(),
            "finished_at": None,
        }
        with _upload_lock:
            # prune old finished jobs (keep last 20)
            finished = [
                jid
                for jid, j in _upload_jobs.items()
                if j.get("status") in ("done", "error")
            ]
            for jid in finished[:-20]:
                _upload_jobs.pop(jid, None)
            _upload_jobs[job_id] = job

        t = threading.Thread(
            target=_run_upload_job,
            args=(job_id, dest, display_name),
            daemon=True,
            name=f"upload-{job_id}",
        )
        t.start()

        return jsonify(
            {
                "ok": True,
                "job_id": job_id,
                "poll": f"/api/library/upload/{job_id}",
                "message": "Upload started — poll for progress",
            }
        )
    except Exception as e:
        return jsonify({"ok": False, "error": f"{type(e).__name__}: {e}"}), 500


@app.get("/api/library/upload/<job_id>")
def api_library_upload_status(job_id: str):
    since = int(request.args.get("since") or 0)
    with _upload_lock:
        job = _upload_jobs.get(job_id)
        if not job:
            return jsonify({"ok": False, "error": "unknown job_id"}), 404
        snap = _job_snapshot(job, since=max(0, since))
    snap["ok"] = True
    return jsonify(snap)


# ---------------------------------------------------------------------------
# Bot ↔ Console link (Render-to-Render internal API)
# ---------------------------------------------------------------------------

_bot_events: list[dict[str, Any]] = []
_BOT_EVENTS_MAX = 100


def _check_internal_token() -> bool:
    import hmac

    expected = (
        os.getenv("INTERNAL_SERVICE_TOKEN")
        or _read_env().get("INTERNAL_SERVICE_TOKEN")
        or ""
    ).strip()
    if not expected:
        return False
    auth = request.headers.get("Authorization") or ""
    got = auth[7:].strip() if auth.lower().startswith("bearer ") else auth
    got = got or (request.headers.get("X-Notbook-Token") or "").strip()
    return bool(got) and hmac.compare_digest(got, expected)


@app.get("/api/link/status")
def api_link_status():
    env = _read_env()
    for k, v in env.items():
        if v and k not in os.environ:
            os.environ[k] = v
    from link_client import bot_base_url, console_base_url, link_configured

    out = {
        "ok": True,
        "configured": link_configured(),
        "bot_base_url": bot_base_url(),
        "console_base_url": console_base_url()
        or (os.getenv("RENDER_EXTERNAL_URL") or "").rstrip("/"),
        "token_set": bool(
            (env.get("INTERNAL_SERVICE_TOKEN") or os.getenv("INTERNAL_SERVICE_TOKEN") or "").strip()
        ),
        "on_render": bool(os.getenv("RENDER")),
        "recent_bot_events": list(reversed(_bot_events[-20:])),
    }
    return jsonify(out)


@app.post("/api/link/pull/bot")
def api_link_pull_bot():
    """Pull status / books / config from the linked bot service."""
    body = request.get_json(force=True, silent=True) or {}
    what = (body.get("what") or "status").strip()
    env = _read_env()
    for k, v in env.items():
        if v and k not in os.environ:
            os.environ[k] = v
    try:
        from link_client import bot_request

        path_map = {
            "status": "/internal/status",
            "ping": "/internal/ping",
            "config": "/internal/config",
            "books": "/internal/library/books",
        }
        path = path_map.get(what)
        if not path:
            return jsonify({"ok": False, "error": f"unknown what={what}"}), 400
        data = bot_request("GET", path)
        return jsonify({"ok": True, "what": what, "data": data})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.post("/api/link/push/bot")
def api_link_push_bot():
    """Push action to bot: cache_clear | library_refresh | event."""
    body = request.get_json(force=True, silent=True) or {}
    action = (body.get("action") or "").strip()
    env = _read_env()
    for k, v in env.items():
        if v and k not in os.environ:
            os.environ[k] = v
    try:
        from link_client import bot_request

        if action == "cache_clear":
            data = bot_request("POST", "/internal/cache/clear", body={})
        elif action == "library_refresh":
            data = bot_request("POST", "/internal/library/refresh", body={})
        elif action == "event":
            data = bot_request(
                "POST",
                "/internal/webhook/console",
                body=body.get("payload") or {"event": body.get("event") or "ping"},
            )
        else:
            return jsonify({"ok": False, "error": "action: cache_clear|library_refresh|event"}), 400
        return jsonify({"ok": True, "action": action, "data": data})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@app.post("/api/link/save")
def api_link_save():
    """Save BOT_BASE_URL + INTERNAL_SERVICE_TOKEN (+ optional CONSOLE_BASE_URL)."""
    body = request.get_json(force=True, silent=True) or {}
    env = _read_env()
    if "BOT_BASE_URL" in body:
        env["BOT_BASE_URL"] = str(body.get("BOT_BASE_URL") or "").rstrip("/")
    if "CONSOLE_BASE_URL" in body:
        env["CONSOLE_BASE_URL"] = str(body.get("CONSOLE_BASE_URL") or "").rstrip("/")
    if "INTERNAL_SERVICE_TOKEN" in body and body.get("INTERNAL_SERVICE_TOKEN"):
        # don't wipe with empty/masked
        tok = str(body["INTERNAL_SERVICE_TOKEN"])
        if "…" not in tok and not (set(tok) <= {"*"}):
            env["INTERNAL_SERVICE_TOKEN"] = tok
    _write_env(env)
    # also set process env for this process
    for k in ("BOT_BASE_URL", "CONSOLE_BASE_URL", "INTERNAL_SERVICE_TOKEN"):
        if env.get(k):
            os.environ[k] = env[k]
    return jsonify({"ok": True, "message": "link settings saved to .env"})


@app.get("/api/internal/status")
def api_internal_console_status():
    """Bot → console: pull console health (auth required)."""
    if not _check_internal_token():
        return jsonify({"ok": False, "error": "unauthorized"}), 401
    env = _read_env()
    return jsonify(
        {
            "ok": True,
            "service": "notbook-console",
            "on_render": bool(os.getenv("RENDER")),
            "external_url": os.getenv("RENDER_EXTERNAL_URL") or "",
            "bot_base_url": (env.get("BOT_BASE_URL") or "").rstrip("/"),
            "token_set": bool((env.get("INTERNAL_SERVICE_TOKEN") or "").strip()),
            "upload_jobs": len(_upload_jobs),
            "bot_events": len(_bot_events),
        }
    )


@app.post("/api/internal/webhook/bot")
def api_internal_webhook_bot():
    """Bot → console webhook."""
    if not _check_internal_token():
        return jsonify({"ok": False, "error": "unauthorized"}), 401
    body = request.get_json(force=True, silent=True) or {}
    event = {
        "event": body.get("event") or "unknown",
        "service": body.get("service") or "bot",
        "payload": body.get("payload") or {},
        "ts": body.get("ts") or time.time(),
    }
    _bot_events.append(event)
    if len(_bot_events) > _BOT_EVENTS_MAX:
        del _bot_events[: len(_bot_events) - _BOT_EVENTS_MAX]
    return jsonify({"ok": True, "received": event["event"]})


@app.get("/api/deploy/guide/<target>")
def api_deploy_guide(target: str):
    guides = {
        "local": {
            "title": "LOCAL",
            "suitable": True,
            "steps": [
                "Fill Secrets + Config tabs and SAVE.",
                "pip install -r requirements.txt",
                "LOCAL → START BOT (or: python main.py)",
                "Admin: send PDF with caption 'ingest Book Name'",
            ],
        },
        "docker": {
            "title": "DOCKER",
            "suitable": True,
            "steps": [
                "Generate Artifacts (writes docker-compose.yml).",
                "Ensure .env exists in project root.",
                "docker compose -f deploy_artifacts/docker-compose.yml up -d --build",
                "docker logs -f notbook-bot",
            ],
        },
        "render": {
            "title": "RENDER",
            "suitable": True,
            "note": "Free tier sleeps; polling pauses until HTTP wake.",
            "steps": [
                "Push repo to GitHub.",
                "Render → New → Blueprint or Web Service.",
                "Build: pip install -r requirements.txt | Start: python main.py",
                "Set env vars from Secrets tab.",
                "Optional: use deploy_artifacts/render.yaml",
            ],
        },
        "railway": {
            "title": "RAILWAY",
            "suitable": True,
            "steps": [
                "New Project → Deploy from GitHub.",
                "Add variables from Secrets.",
                "Use Dockerfile or Python start: python main.py",
                "railway.toml is in deploy_artifacts/",
            ],
        },
        "heroku": {
            "title": "HEROKU",
            "suitable": True,
            "steps": [
                "heroku create your-app",
                "heroku config:set KEY=value …",
                "git push heroku main",
                "Procfile: web: python main.py",
            ],
        },
        "fly": {
            "title": "FLY.IO",
            "suitable": True,
            "steps": [
                "fly launch --config deploy_artifacts/fly.toml",
                "fly secrets set …",
                "fly deploy",
                "Keep min_machines_running=1 so bot stays up.",
            ],
        },
        "vps": {
            "title": "VPS / SYSTEMD",
            "suitable": True,
            "steps": [
                "Provision Ubuntu/Debian VPS.",
                "Copy project to /opt/notbook",
                "Create venv, pip install -r requirements.txt",
                "Place .env, install notbook.service",
                "systemctl enable --now notbook",
            ],
        },
        "vercel": {
            "title": "VERCEL",
            "suitable": False,
            "note": "Serverless cold starts + no long-polling. Do not host the bot here.",
            "steps": [
                "Use Render, Railway, Fly, Docker, or VPS instead.",
                "If you need a static docs site only, Vercel is fine for HTML — not the bot.",
            ],
        },
    }
    g = guides.get(target.lower())
    if not g:
        return jsonify({"ok": False, "error": "unknown target"}), 404
    return jsonify({"ok": True, "guide": g})


def create_app() -> Flask:
    _ensure_dirs()
    return app


if __name__ == "__main__":
    _ensure_dirs()
    port = int(os.getenv("CONSOLE_PORT", "8787"))
    print(f"Notbook Deploy Console → http://127.0.0.1:{port}")
    app.run(host="127.0.0.1", port=port, debug=False)
